version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "5437:5432"
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=students